name: Extract changed images

on:
  push:
    branches: [ master ]

jobs:
  show_changed_images:
    runs-on: ubuntu-latest
    defaults:
      run:
        # To share shell profile between steps
        # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Detect changed raw images
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}      
        run: |
          # Git files changed
          git diff --name-only refs/heads/master ${{ github.ref }}

          # DVC files changed
          # dvc diff --show-json a_rev b_rev | jq
          # a_rev      Old Git commit to compare (defaults to HEAD)
          # b_rev      New Git commit to compare (defaults to current workspace)
          # dvc diff --show-json 7f43a8b HEAD | jq
          dvc diff --show-json refs/heads/master ${{ github.ref }} | jq